---
application:
  name: "angular-weekly-calendar"
  project: "test-front"
  organization: "Jobs@Risk"
routers:
- name: "main-angular-weekly-calendar"
  routes:
  - application_name: "angular-weekly-calendar"
    paths:
    - "/*"
