---
application:
  name: "angular-weekly-calendar"
  project: "test-angular-calendar"
  organization: "QoveryCommunity"
routers:
- name: "main-angular-weekly-calendar"
  routes:
  - application_name: "angular-weekly-calendar"
    paths:
    - "/*"
